astral-sh/packse

- scenarios/requires-does-not-exist.json
- src/packse/build.py
- src/packse/error.py
- src/packse/scenario.py
- src/packse/view.py
- tests/__snapshots__/test_build.ambr
- tests/__snapshots__/test_scenarios.ambr
- tests/__snapshots__/test_view.ambr
- tests/test_scenarios.py
- Add a "real" scenario: a package that requires any version of another package that does not exist
- Add description support to `Scenario`s
- Add test suite for building and viewing all scenarios in `scenarios/`
- Remove duplicate `dist/` directory from `build/<package>/`
- Include reason for invalid scenario errors
> Add a real scenario

- README.md
- scenarios/requires-incompatible-versions.json
- src/packse/build.py
- src/packse/scenario.py
- src/packse/templates/simple/{{ package-name }}-{{ version }}/pyproject.toml
- tests/__snapshots__/test_build.ambr
- tests/__snapshots__/test_publish.ambr
- tests/__snapshots__/test_scenarios.ambr
The entrypoint package can be installed to "run" the scenario — it has the same name as the scenario for ease of use.
Also:
- Add package description support
- Clarify role of root package
- Add sdist and wheel toggles per version
> Build entrypoint package for each scenario

- src/packse/build.py
- tests/__snapshots__/test_build.ambr
- tests/__snapshots__/test_scenarios.ambr
- tests/common.py
- tests/test_build.py
- tests/test_scenarios.py
We remove stderr from the `build` snapshots because the logging is no longer deterministic.
It seems horrible to try to group logs per thread — maybe another time.
Closes https://github.com/zanieb/packse/issues/14
> Build scenarios in multiple threads

- src/packse/cli.py
- src/packse/error.py
- src/packse/publish.py
- tests/__snapshots__/test_publish.ambr
- tests/common.py
- tests/test_publish.py
Adds retry when a 429 is encountered and better error display in the `publish` CLI.
Unfortunately the rate limit for new projects looks relatively severe at 20 packages / hr
https://github.com/pypi/warehouse/blob/d858a996fe543131931955d8e8cc96b8aa7261a1/warehouse/config.py#L352-L369
Also adds some mocked twine test coverage to `publish`
> Add retry on rate limits to `publish`

- scenarios/example.json
- scenarios/requires-does-not-exist.json
- scenarios/requires-incompatible-versions.json
- src/packse/build.py
- src/packse/scenario.py
- src/packse/view.py
- tests/__snapshots__/test_build.ambr
- tests/__snapshots__/test_publish.ambr
- tests/__snapshots__/test_scenarios.ambr
- tests/__snapshots__/test_view.ambr
Closes #11 #12
Changes `root` from a pointer to the some provided package to a full listing of package requirements.
Also, significantly improves `view`:
- Uses correct tree parts consistently
- Groups package versions by package name
- Separate root package display without versions
- Limits recursion of requirements to avoid redundant display
> Restructure `root` package

- .github/workflows/publish.yaml
- README.md
- src/packse/cli.py
- src/packse/error.py
- src/packse/publish.py
- tests/__snapshots__/test_publish.ambr
- tests/test_publish.py
- Adds `packse publish --index-url <URL>` for publishing to other indices. Tested with a local `devpi` instance.
- Adds `PACKSE_PUBLISH_USERNAME/PASSWORD` instead of requiring the user to configure twine directly.
- We no longer support reading from the `~/.pypirc` file
- Adds timeout to `publish` as it can hang indefinitely if `twine` is not invoked correctly
> Add support for other package indices

- src/packse/cli.py
- src/packse/index.py
- Add display of logs from any uncaptured subprocess failure
- Allow files to exist if using a custom storage path as well as if in the background
- Display the server start command with `-v`
- Send a SIGTERM to the server before SIGKILL on shutdown
Closes https://github.com/zanieb/packse/issues/37
> Improve handling of server errors

- .github/workflows/check.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
[pipx is a pre-installed package manager](https://github.com/actions/runner-images/blob/266f9413d39fc77ade974757b633ef98873c9c21/images/ubuntu/Ubuntu2204-Readme.md#package-management) in the latest Ubuntu GHA runner images.
Since it is a recommended way of installing Poetry, because it creates a separate environment, I changed the workflows to install Poetry through pipx.
In order to leverage `poetry.lock`-dependent [caching feature](https://github.com/actions/setup-python/blob/e9d6f990972a57673cdb72ec29e19d42ba28880f/docs/advanced-usage.md#caching-packages) offered by [actions/setup-python](https://github.com/actions/setup-python), I moved the Poetry setups before the `setup-python` step is performed.
Additionally, I bumped actions/setup-python to the latest v5 version (see …
> Use pipx for installing Poetry

- scenarios/requires-python.json
- src/packse/scenario.py
- src/packse/view.py
- tests/__snapshots__/test_build.ambr
- tests/__snapshots__/test_inspect.ambr
- tests/__snapshots__/test_list.ambr
- tests/__snapshots__/test_publish.ambr
- tests/__snapshots__/test_scenarios.ambr
- tests/__snapshots__/test_view.ambr
Adds an `environment` to scenarios allowing a current Python version to be specified.
Adds support for displaying `requires-python` in `packse view`
Adds test scenarios for `requires-python` incompatibilities.
The `environment` can be used for platform information and such in the future, if we want to mock that.
> Add scenarios for `requires-python` incompatibilities

- .github/workflows/publish.yaml
Adds a new cron job for the `Publish` job since publishing can fail with a rate limit timeout of one hour. Otherwise, on rate limit we don't get the merged packages on `main` until another commit is merged.
To avoid wasting GHA compute and PyPI bandwidth, it'll only run if the last run failed.
This should have no effect on pull requests.
> Schedule publishing retries

- src/packse/build.py
- src/packse/cli.py
- src/packse/error.py
- tests/__snapshots__/test_build_pkg.ambr
- tests/__snapshots__/test_root.ambr
- tests/test_build_pkg.py
Allows building dummy package distributions without writing a scenario
e.g.
```
❯ packse build-pkg hello 1.0.0 --rm -t foo -t bar
Generated project for 'hello-1.0.0'
Built package 'hello-1.0.0' in 0.09s
Linked distribution to dist/hello/hello-1.0.0-bar.whl
Linked distribution to dist/hello/hello-1.0.0-foo.whl
Linked distribution to dist/hello/hello-1.0.0.tar.gz
Done in 98.87ms
```
> Add packse `build-pkg` command to build a single version for testing

- src/packse/build.py
- src/packse/scenario.py
- src/packse/view.py
- tests/__snapshots__/test_inspect.ambr
- tests/__snapshots__/test_list.ambr
- tests/__snapshots__/test_scenarios.ambr
Instead of repeatedly parsing these as needed, we parse them in the `Scenario` type which is cleaner.
> Parse specifiers into requirements on scenario load

- src/packse/fetch.py
This fixes a test failure on current `main` where
`packse fetch --ref 0.1.0` was failing. Namely, `packse fetch` does a
shallow clone, which means not all tags are available. Since `0.2.0` has
been tagged, the shallow clone only has the `0.2.0` tag available.
It's not clear what the right fix is here. I assume it is non-ideal to
have a deep clone here, but it's also not clear to me whether we want
`packse fetch --ref 0.1.0` to always work. If so, then I think we
probably need a deep clone?
We can adjust this of course in the future, but I made this change to
unblock CI.
> fetch: don't do a shallow clone

- scenarios/local.json
This improves our coverage for installing packages involving versions
with local segments.
~~This PR also adds a new optional `expected.ignore` property. When it's
true, it's expected that the scenario will be ignored in downstream
tools. For example, if the scenario doesn't pass yet even though it is
expected or desired to.~~
I've backed out the change to add `expected.ignore` to the schema, and
instead opted to mark tests as skipped on `uv`'s end in https://github.com/astral-sh/uv/pull/2022.
This makes sense to me since this de-couples the current state of `uv` from
packse scenarios.
> add a collection of tests that use local versions

- .github/workflows/publish.yaml
Since packse currently has some scenarios with versions using local
segments, this CI step is going to continuously fail. We should either
figure out another way to deal with local versions or change where we
publish packages to.
> ci: temporarily disable periodic publishing

- CONTRIBUTING.md
- src/packse/templates/package/{{ package-name }}-{{ version }}/pyproject.toml
- tests/__snapshots__/test_build.ambr
- tests/__snapshots__/test_scenarios.ambr
I noticed that when using a requirement like
```
c<2.0.0 ; sys_platform == 'linux'
```
then the single quotes seem to get rewritten as double quotes. And since
the TOML template just prints the value as-is without any escaping, it
ends up producing an invalid TOML file.
I do wonder whether a better fix here would be to abdicate templates and
use a proper TOML serializer from an in-memory data structure, but this
fix is probably good enough for now. Namely, we use triply quoted TOML
strings. The only way this can go wrong is if the requirement contains
three single quotes in succession.
> templates/package: fix template to use triple quotes

- scenarios/fork/basic.toml
- scenarios/fork/marker-accrue.toml
- scenarios/fork/marker-selection.toml
- scenarios/fork/marker-track.toml
- scenarios/fork/non-fork-marker-transitive.toml
- scenarios/fork/non-local-fork-marker-direct.toml
- scenarios/fork/non-local-fork-marker-transitive.toml
- src/packse/scenario.py
- src/packse/templates/package/{{ package-name }}-{{ version }}/pyproject.toml
- tests/__snapshots__/test_build.ambr
- tests/__snapshots__/test_build_pkg.ambr
- tests/__snapshots__/test_inspect.ambr
- tests/__snapshots__/test_scenarios.ambr
This adds `resolve_options.universal` to the packse schema, as well as an initial set of tests for the universal resolver.
> add initial support for universal resolver tests

- .github/workflows/release.yaml
Previously, we were only publishing `*.json` scenarios. But with the new
fork tests being writtin in TOML files in sub-directories, we should
just publish everything in `scenarios/`.
> ci: publish all scenarios

- scenarios/fork/marker-disjoint.toml
The description in the test explains things, but this is just adding a
basic test to ensure that forking in the universal resolver is done by
inspecting marker disjointness.
> scenarios: add basic test for testing marker disjointness

- scenarios/fork/requires-python-full-prerelease.toml
- scenarios/fork/requires-python-full.toml
- scenarios/fork/requires-python.toml
This tests the interaction between `Requires-Python` and marker
expressions like `python_version` and `python_full_version`. In both of
these tests, the `a` dependency should be completely ignored because its
corresponding marker expression will never evaluate to true.
> scenarios: add tests for Requires-Python

- scenarios/fork/requires-python-full-prerelease.toml
- scenarios/fork/requires-python-full.toml
- scenarios/fork/requires-python.toml
Without this, the tests generated in `uv` seem to default to using
`3.8`, which in turn doesn't work with a `Requires-Python` of 3.10.
We could change the version numbers here to work with the `3.8` default,
but it seems better to fully specify which Python is being used.
> scenarios: add Python environment to Requires-Python tests

- scenarios/fork/requires-python-full-prerelease.toml
- scenarios/fork/requires-python-full.toml
- scenarios/fork/requires-python.toml
This was an oversight when I initially wrote the tests. They are of
course satisfiable. We are just checking to make sure the `a` dependency
is filtered out by our `Requires-Python` specifier.
> scenarios: mark requires-python tests as satisfiable

- scenarios/fork/marker-inherit-combined-allowed.toml
- scenarios/fork/marker-inherit-combined-disallowed.toml
- scenarios/fork/marker-inherit-combined.toml
- scenarios/fork/marker-inherit-isolated.toml
- scenarios/fork/marker-inherit-transitive.toml
- scenarios/fork/marker-inherit.toml
- scenarios/fork/marker-limited-inherit.toml
- uv.lock
This adds a number of tests to check that marker expressions are correctly
propagated through resolver forks *and* that they are used to filter out
dependencies that are impossible to visit during an installation.
> add tests for tracking markers across forks

- scenarios/fork/allows-non-conflicting-non-overlapping-dependencies.toml
- scenarios/fork/allows-non-conflicting-repeated-dependencies.toml
- scenarios/fork/conflict-unsatisfiable.toml
These tests were motivated by @konstin's question here:
https://github.com/astral-sh/uv/pull/4339#discussion_r1642622391
> scenarios: add more tests for resolver forks tracking markers

- scenarios/fork/allows-non-conflicting-non-overlapping-dependencies.toml
- scenarios/fork/allows-non-conflicting-repeated-dependencies.toml
- scenarios/fork/conflict-unsatisfiable.toml
- scenarios/fork/filter-sibling-dependencies.toml
This test is a reproduction of the issue observed in
https://github.com/astral-sh/uv/issues/4414, but "minimized" to a packse
scenario.
> scenarios: add test ensuring sibling dependencies get filtered in a fork

- uv.lock
Now that 0.2.13 is out, we can update the lock file. This trims a number
of entries due to Requires-Python filtering.
> uv: update uv.lock

- tests/__snapshots__/test_build.ambr
- tests/__snapshots__/test_build_pkg.ambr
- tests/__snapshots__/test_scenarios.ambr
- uv.lock
There were some incompatible changes since the lockfile was last updated.
I didn't intend to update the versions but the incompatible changes means that the lockfile wasn't used as preferences.
I've updated the wheel hashes, they changed due to some updated build dependencies.
> Update lockfile for latest uv release

- scenarios/fork/incomplete-markers.toml
We're currently (https://github.com/astral-sh/uv/issues/4732) failing to install `c` from the added scenario:
```
$ echo "fork-incomplete-markers-8137fed5" | uv pip compile --index-url http://127.0.0.1:3141 -p 3.9 --universal -
Resolved 4 packages in 38ms
fork-incomplete-markers-8137fed5==0.0.0
fork-incomplete-markers-a-8137fed5==1.0.0 ; python_version < '3.10'
fork-incomplete-markers-a-8137fed5==2.0.0 ; python_version >= '3.11'
fork-incomplete-markers-b-8137fed5==1.0.0
```
This is one particular scenario that we need to test for solving https://github.com/astral-sh/uv/issues/4732
I had to update the lockfile for the recent uv lockfile changes, split out to #199 which removes it from the diff here.
> Add failing incomplete markers scenarios

- scenarios/fork/conflict-in-fork.toml
Add a scenario where we fail after forking. The error message is already not bad:
```
× No solution found when resolving dependencies:
╰─▶ Because only fork-basic-b-03509d5c==1.0.0 is available and fork-basic-b-03509d5c==1.0.0 depends on fork-basic-d-03509d5c==1,
we can conclude that all versions of fork-basic-b-03509d5c depend on fork-basic-d-03509d5c==1.
And because fork-basic-c-03509d5c==1.0.0 depends on fork-basic-d-03509d5c==2 and only fork-basic-c-03509d5c==1.0.0 is
available, we can conclude that all versions of fork-basic-b-03509d5c and all versions of fork-basic-c-03509d5c are
incompatible.
And because fork-basic-a-03509d5c{sys_platform == 'darwin'}==1.0.0 depends on fork-basic-b-03509d5c and fork-basic-c-03509d5c,
we can conclude that fork-basic-a-03509d5c{sys_platform == …
```
> Add conflict in fork scenario

- scenarios/fork/preferences-dependent-forking-conflicting.toml
- scenarios/fork/preferences-dependent-forking.toml
- uv.lock
In the first scenario, `preferences-dependent-forking`, we show how the resolution can be different the second time because we don't fork anymore because the preferences from the lockfile make us skip the fork point. This scenario is inspired by the same happening in the `transformer` repo, where a single universal resolution leads to a more desirable lock without duplicate versions.
Consider a fresh run without preferences:
* We start with cleaver 2
* We fork
* We reject cleaver 2
* We find a cleaver 1 solution in fork 1 with foo 2 with bar 1
* We find a cleaver 1 solution in fork 2 with foo 1 with bar 2
* We write cleaver 1, foo 1, foo 2, bar 1 and bar 2 to the lockfile
In a subsequent run, we read the preference cleaver 1 from the lockfile (the preferences for foo and bar don't …
> Add forking scenarios that are unstable with preferences

- scenarios/fork/overlapping-markers-basic.toml
The description explains its utility and how it fails on current `uv`.
> scenarios/fork: add basic overlapping markers test case

- scenarios/fork/preferences-dependent-forking-bistable.toml
- scenarios/fork/preferences-dependent-forking-tristable.toml
Another test for the resolver instability.
> This test contains a bistable resolution scenario when not using ahead-of-time
> splitting of resolution forks: We meet one of two fork points depending on the
> preferences, creating a resolution whose preferences lead us the other fork
> point.
>
> In the first case, we are in cleaver 2 and fork on `sys_platform`, in the
> second case, we are in foo 1 or bar 1 amd fork over `os_name`.
>
> First case: We select cleaver 2, fork on `sys_platform`, we reject cleaver 2
> (missing fork `os_name`), we select cleaver 1 and don't fork on `os_name` in
> `fork-if-not-forked`, done.
> Second case: We have preference cleaver 1, fork on `os_name` in
> `fork-if-not-forked`, we reject cleaver 1, we select cleaver 2, we fork on
> `sys_platform`, we accept …
> Add bistable preference-dependent forking scenario

- scenarios/fork/fork-upgrade.toml
The scenario checks that we discard fork markers when using `--upgrade`. Test case for #5817.
> Add fork-upgrade scenario

- .github/workflows/check.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
This is required to properly target them in the required checks in the github actions settings.
> Prefix packse github actions tasks

- .github/workflows/build.yaml
- .github/workflows/release.yaml
CI was complaining:
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3, actions/setup-python@v4. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> Update deprecated actions

- scenarios/fork/requires-python-patch-overlap.toml
For whatever reason this is confusing Clippy on 1.81.
> Modify line breaks for patch test

- .github/workflows/check.yaml
- .prettierrc
- CONTRIBUTING.md
- package-lock.json
- package.json
- scenarios/examples/example.json
- scenarios/examples/example.toml
- scenarios/examples/example.yaml
Follow up from https://github.com/astral-sh/packse/pull/211#issuecomment-2272830605
> feat: enable prettier for scenarios

- scenarios/local/local-greater-than-or-equal.toml
- scenarios/local/local-less-than-or-equal.toml
- scenarios/local/local-not-used-with-sdist.toml
- scenarios/local/local-simple.toml
- scenarios/local/local-transitive-backtrack.toml
- scenarios/local/local-transitive-conflicting.toml
- scenarios/local/local-transitive-confounding.toml
- scenarios/local/local-transitive-greater-than-or-equal.toml
- scenarios/local/local-transitive-greater-than.toml
- scenarios/local/local-transitive-less-than-or-equal.toml
- scenarios/local/local-transitive-less-than.toml
- scenarios/local/local-transitive.toml
This ensures that we get ordering right _between_ local versions.
> Add multiple local versions to local version tests

- .github/workflows/build.yaml
- .gitignore
`pkg_resources` are deprecated in favor of `importlib.metadata`.
Does this allow removing the setuptools dependency or is this used elsewhere?
> Remove deprecate pkg_resources

- scenarios/backtracking/wrong-backtracking-basic.toml
- src/packse/build.py
Scenario for https://github.com/astral-sh/uv/issues/8157.
There are two packages, `a` and `b`. We select `a` with `a==2.0.0` first, and then `b`, but `a==2.0.0` conflicts with all new versions of `b`, so we backtrack through versions of `b`.
We need to detect this conflict and prioritize `b` over `a` instead of backtracking down to the too old version of `b==1.0.0` that doesn't depend on `a` anymore.
> Add wrong-backtracking scenario

- scenarios/wheels/no-sdist-no-wheels-with-matching-abi.toml
- scenarios/wheels/no-sdist-no-wheels-with-matching-platform.toml
- scenarios/wheels/no-sdist-no-wheels-with-matching-python.toml
- src/packse/scenario.py
- tests/__snapshots__/test_inspect.ambr
In uv, we're starting to show "compatible tags" in error messages. If we don't set the Python platform, then the displayed tag will vary based on the host machine.
> Allow scenarios to set a Python platform

- scenarios/wheels/no-sdist-no-wheels-with-matching-abi.toml
- scenarios/wheels/no-sdist-no-wheels-with-matching-python.toml
I'm making our tag-parsing stricter, and these now get filtered out. We should use real (but non-matching) tags.
> Use valid wheel tags for no-matching tests

- src/packse/templates/package/{{ package-name }}-{{ version }}/pyproject.toml
Prevents
```toml
[packages.psycopg.versions."1.0.0".extras]
binary = ["psycopg-binary; implementation_name != 'pypy'"]
```
from becoming
```toml
[project.optional-dependencies]
binary = [
"marker-variants-have-different-extras-psycopg-binary; implementation_name != "pypy"",
]
```
Same fix as https://github.com/astral-sh/packse/pull/175
> Fix markers in optional dependencies

- scenarios/fork/conflict-in-fork.toml
This avoids platform specific diagnostics for https://github.com/astral-sh/uv/pull/13455
> Don't use real platforms for conflict-in-fork

- scenarios/tag_and_markers/virtual-package-extra-priorities.toml
- scenarios/tag_and_markers/virtual-package-marker-priorities.toml
These test cases were intended for https://github.com/astral-sh/uv/pull/10935. They still test the virtual package priorities, even though they are not observable in the resolution outcome in the current resolver usage. They can be used to observe virtual package prioritization in resolver verbose mode, so I'd keep them in case we have to follow-up to https://github.com/astral-sh/uv/pull/10935
> Add test cases for virtual package priorities

- scenarios/requires_python/python-greater-than-current-patch.toml
Python 3.9.12 is as twice as large as other Pythons on Windows (~40MB vs ~20MB), and there's only one test using it. With this change, we can drop it from the uv `.python-versions`.
> Drop Python 3.9.12 requirement
