.github/workflows/publish.yaml

Fixes publish on `main` introduced in #3

Publish on merge to main branch

---

src/packse/cli.py
src/packse/publish.py
tests/__snapshots__/test_publish.ambr
tests/test_publish.py

Run `publish` in parallel

---

src/packse/scenario.py
tests/__snapshots__/test_build.ambr
tests/__snapshots__/test_list.ambr
tests/__snapshots__/test_publish.ambr
tests/__snapshots__/test_scenarios.ambr
tests/__snapshots__/test_view.ambr

This was incorrectly excluded, leading to hash collisions for changes like #50

Include `root` in scenario hash

---

scenarios/prereleases.json
tests/__snapshots__/test_inspect.ambr
tests/__snapshots__/test_list.ambr
tests/__snapshots__/test_scenarios.ambr

Add pre-release scenarios

---

scenarios/example.json
scenarios/prereleases.json
scenarios/requires-does-not-exist.json
scenarios/requires-incompatible-versions.json
scenarios/requires-python.json
src/packse/scenario.py
tests/__snapshots__/test_build.ambr
tests/__snapshots__/test_inspect.ambr
tests/__snapshots__/test_list.ambr
tests/__snapshots__/test_publish.ambr
tests/__snapshots__/test_scenarios.ambr
tests/__snapshots__/test_view.ambr

Adds scenario metadata with the expected result of resolution including satisfiability, installed package versions, and an optional explanation.

Add expected results to scenarios

---

scenarios/prereleases.json
tests/__snapshots__/test_inspect.ambr
tests/__snapshots__/test_list.ambr
tests/__snapshots__/test_scenarios.ambr

Adds the missing case from #57

Add additional prerelease case

---

scenarios/prereleases.json
src/packse/scenario.py
tests/__snapshots__/test_inspect.ambr
tests/__snapshots__/test_list.ambr
tests/__snapshots__/test_scenarios.ambr

Allows pre-releases to be selected globally instead of with an opt-in specifier.

Add environment option for global prerelease selector

---

scenarios/excluded.json
tests/__snapshots__/test_inspect.ambr
tests/__snapshots__/test_list.ambr
tests/__snapshots__/test_scenarios.ambr

Adds scenarios for cases where a version or range of versions are excluded for some reason.
These are focused on error messages explaining why solving was not possible.

Add scenarios for excluded versions

---

scenarios/requires-python.json
tests/__snapshots__/test_inspect.ambr
tests/__snapshots__/test_list.ambr
tests/__snapshots__/test_scenarios.ambr

Fix incompatible tag

---

scenarios/wheels.json
src/packse/scenario.py
tests/__snapshots__/test_inspect.ambr
tests/__snapshots__/test_list.ambr
tests/__snapshots__/test_scenarios.ambr

For test coverage of `--no-binary` / `--only-binary` behaviors

Add no-build and no-binary resolver options

---

scenarios/yanked.json
src/packse/build.py
src/packse/publish.py
src/packse/scenario.py
src/packse/view.py
tests/__snapshots__/test_inspect.ambr
tests/__snapshots__/test_list.ambr
tests/__snapshots__/test_scenarios.ambr

Requires manual yank of packages after publish. May they be very immutable..

Add yanked package support

---

scenarios/wheels.json
tests/__snapshots__/test_inspect.ambr
tests/__snapshots__/test_list.ambr
tests/__snapshots__/test_scenarios.ambr

ref
https://github.com/pypi/warehouse/blob/9461adba23b3a3ef335deb884a8c72529a77e53f/warehouse/forklift/legacy.py#L127C36-L127C43
https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/

Use a valid platform for the no wheel cases

---

src/packse/scenario.py

Preventing bugs like https://github.com/zanieb/packse/pull/105

Forbid unknown fields in scenarios

---

scenarios/extras.json
tests/__snapshots__/test_inspect.ambr
tests/__snapshots__/test_scenarios.ambr

From https://github.com/astral-sh/uv/pull/1435

Fix missing word in scenarios/extras.json

---

vendor/links.html

Add find-links directory of build deps

---

src/packse/templates/package/{{ package-name }}-{{ version }}/.gitignore
tests/__snapshots__/test_build.ambr
tests/__snapshots__/test_build_pkg.ambr
tests/__snapshots__/test_scenarios.ambr

https://github.com/pypa/hatch/issues/1273 bit us again, unfortunately we need to just populate this to be sure we stop upward traversal on build.

Add gitignore to templates

---

scenarios/example.json
tests/__snapshots__/test_inspect.ambr

Closes https://github.com/astral-sh/packse/issues/157

Fix expected outcome in example scenario

---

scenarios/local.json

Closes https://github.com/astral-sh/packse/issues/159.

Fix expectation for local-transitive-confounding

---

scenarios/fork/remaining-universe-partitioning.toml

The description for the scenario attempts to explain the utility of the
test.
This was added in response to a question here:
https://github.com/astral-sh/uv/pull/5163#discussion_r1691703519

scenarios/fork: add nested "remaining universe" test

---

src/packse/scenario.py

Unlike json scenarios, toml and yaml scenarios have multi-line description fields, in which we can write proper markdown. Textwrap doesn't understand markdown and mangles it. To fix https://github.com/astral-sh/uv/pull/5441#discussion_r1691470051, we stop textwrapping toml and yaml files.
I've tested this locally and the snapshots look better, due to https://github.com/astral-sh/uv/issues/5475 is somewhat incomplete though: https://github.com/astral-sh/uv/pull/5441.

Don't textwrap toml scenarios

---

tests/common.py
tests/test_build.py
tests/test_inspect.py
tests/test_list.py
tests/test_publish.py
tests/test_scenarios.py
tests/test_view.py

This was blocking #214.
Should we pin ruff in the future?

Fix ruff isort errors

---

uv.lock

Update to the stable lockfile. No version updates.

Update lockfile to uv v0.3.0

---

scenarios/tag-and-markers.json

Add tests for https://github.com/astral-sh/uv/pull/6959 and https://github.com/astral-sh/uv/pull/6961.
Tested with:
```toml
[project]
name = "foo"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["unreachable-package", "unreachable-wheels", "requires-python-wheels"]
[tool.uv]
index-url = "http://localhost:3141"
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```
Lockfile:
```toml
version = 1
requires-python = ">=3.10"
[[package]]
name = "foo"
version = "0.1.0"
source = { editable = "." }
dependencies = [
{ name = "requires-python-wheels" },
{ name = "unreachable-package" },
{ name = "unreachable-wheels" },
]
[package.metadata]
requires-dist = [
{ name = "requires-python-wheels" },
{ name = "unreachable-package" },
{ name = "unreachable-wheels" },
] …
```

Add test for unreachable packages and wheels

---

scenarios/tag-and-markers.json

Follow-up for https://github.com/astral-sh/packse/pull/217

Use correct python version in requires-python-wheels

---

.github/workflows/release.yaml

Publish to production PyPI on release

---

scenarios/prereleases/package-prereleases-boundary.toml
scenarios/prereleases/package-prereleases-global-boundary.toml
scenarios/prereleases/requires-package-only-prereleases-in-range-global-opt-in.toml
scenarios/requires_python/compatible-python-incompatible-override.toml
scenarios/requires_python/incompatible-python-compatible-override-available-no-wheels.toml
scenarios/requires_python/incompatible-python-compatible-override-no-compatible-wheels.toml
scenarios/requires_python/incompatible-python-compatible-override-other-wheel.toml
scenarios/requires_python/incompatible-python-compatible-override-unavailable-no-wheels.toml
scenarios/requires_python/incompatible-python-compatible-override.toml
scenarios/requires_python/python-greater-than-current-backtrack.toml
scenarios/requires_python/python-greater-than-current-excluded.toml
scenarios/requires_python/python-greater-than-current-many.toml
scenarios/requires_python/python-greater-than-current-patch.toml
scenarios/requires_python/python-greater-than-current.toml
scenarios/requires_python/python-less-than-current.toml
scenarios/requires_python/python-patch-override-no-patch.toml
scenarios/requires_python/python-patch-override-patch-compatible.toml
scenarios/tag_and_markers/requires-python-wheels.toml
scenarios/tag_and_markers/unreachable-package.toml
scenarios/tag_and_markers/unreachable-wheels.toml
scenarios/wheels/no-binary.toml
scenarios/wheels/no-build.toml
scenarios/wheels/no-wheels-no-build.toml
scenarios/wheels/only-wheels-no-binary.toml

https://github.com/astral-sh/packse/pull/211#issuecomment-2453676905
Adds missing `resolver_options` and `environment` lost from json to toml conversion

fix: add missing environment and resolver_options

---

scenarios/wheels/no-sdist-no-wheels-with-matching-abi.toml

See: https://github.com/astral-sh/uv/pull/12154

Update GraalPy tag
